title: Federalist Homepage
name: Federalist Homepage
theme: uswds-jekyll

# Configuration for Google Analytics, add your UA code here:
google_analytics_ua: UA-48605964-31

# Configuration for DAP, add your agency ID here:
dap_agency: GSA

# To enable search, uncomment the search section
# You will need to setup a search account with search.gov
# https://search.usa.gov/signup
# Your search_site_handle value is from the search.gov settings page.


search_site_handle: federalist

support_email: federalist-support@gsa.gov

collections:
  pages:
    output: true
    permalink: /:path/

scripts:
  - /assets/uswds/js/uswds.min.js
  - /assets/js/index.js

relative_permalinks: false


exclude:
  - /coverage
  - /README.md
  - /Gemfile
  - /Gemfile.lock
  - /PULL_REQUEST_TEMPLATE.md
  - /README.md
  - /LICENSE.md
  - /CONTRIBUTING.md
  - /spec/*
  
styles:
  - /assets/css/site.css

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  
# GitHub information
# This is used for adding an edit this page link to the footer
github:
  organization: 18F
  repository: federalist.18f.gov
  default_branch: master
