name: Federalist Documentation
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor
include:
  - _navigation.json

permalink: pretty
highlighter: rouge
incremental: true
markdown: redcarpet
redcarpet:
  extensions: [with_toc_data]

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F - Federalist
  url: https://federalist.18f.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /uploads/logo.svg
logoalt: Federalist logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: About Federalist
  url: index.html
  internal: true
- text: Using Federalist
  url: pages/using-federalist/
  internal: true
  children:
  - text: Launch Checklist
    url: launch-checklist/
    internal: true
  - text: Customer Responsibilities
    url: customer-responsibilities/
    internal: true
- text: Content Guide
  url: pages/content-guide/
  internal: true
  children:
  - text: Writing content for your homepage
    url: writing-content-for-your-federalist-homepage/
    internal: true
  - text: Writing about your team
    url: best-practices-for-writing-who-we-are/
    internal: true
  - text: Writing about your research
    url: best-practices-for-writing-what-we-do/
    internal: true
  - text: Writing clear contact forms
    url: contact-forms/
    internal: true
  - text: Best practices for content
    url: best-practices-for-content/
    internal: true
- text: Custom Templates
  url: pages/custom-templates/
  internal: true
- text: How Federalist Works
  url: pages/how-federalist-works/
  internal: true
  children:
  - text: How Custom URLs work
    url: custom-urls/
    internal: true
  - text: Included with Federalist
    url: included-with-federalist/
    internal: true
  - text: Node on Federalist
    url: node-on-federalist/
    internal: true
  - text: Deploying Federalist
    url: deploying-federalist/
    internal: true
  - text: cloud.gov Setup
    url: cloud-gov-setup/
    internal: true
  - text: Running Federalist locally
    url: running-federalist-locally/
    internal: true

repos:
- name: Federalist
  description: Documentation repository
  url: https://github.com/18F/federalist-docs

back_link:
  url: "https://federalist.18f.gov/"
  text: Back to Federalist

google_analytics_ua: UA-48605964-19

defaults:
- scope:
    path: ""
  values:
    layout: "docs"
stylesheets:
- /assets/uswds/css/uswds.css
scripts:
- /assets/uswds/js/uswds.js

